service: characteria-xu # CHANGE THIS SAME AS rootName at constant

provider:
  name: aws
  region: ap-southeast-1
  stage: v1
  ecr:
    images:
      hello-rust-rocket:
        path: ./
  environment:
    IS_LAMBDA_ENV: true
    SENTRY_ENV: production
    SENTRY_IO_DSN: ${env:SENTRY_IO_DSN}
  httpApi:
    cors: true
  deploymentBucket:
    name: xu.chanh

functions:
  main:
    handler: dist/lamda.handler
    architecture: arm64
    memorySize: 1024
    timeout: 10
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: "{proxy+}"
          cors: true
