service: characteria-xu # CHANGE THIS SAME AS rootName at constant
plugins:
  - serverless-offline
  - serverless-jetpack
useDotenv: true

provider:
  name: aws
  region: ap-southeast-1
  stage: v1
  runtime: nodejs16.x
  environment:
    IS_LAMBDA_ENV: true
    SENTRY_ENV: production
    SENTRY_IO_DSN: ${env:SENTRY_IO_DSN}
  httpApi:
    cors: true
  deploymentBucket:
    name: xu.chanh
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
            - dynamodb:Batch*
            - dynamodb:Describe*
          Resource:
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}* # <---- table name
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}*/index/* # <---- indexes

package:
  exclude:
    - "!dist/**"
    - "!node_modules/**"
    - "node_modules/aws-sdk/**"
    - "src/**"
    - "test/**"
    - "*.md"
    - "*.lock"

functions:
  main:
    handler: dist/lamda.handler
    architecture: arm64
    memorySize: 1024
    timeout: 10
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: "{proxy+}"
          cors: true

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: characteria-xu
