name: Serverless Deploy with Docker build & push

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to AWS ECR
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Build and push Docker image
        uses: aws-actions/docker-build-push@v2
        run: |
          serverless deploy

      - name: Success message
        if: success()
        run: echo "Deployment successful!"
